### ISSUE TITLE
mediaTypeSuffix --> mediaTypeExtension

### ISSUE THREAD

**Issue by aldonline** [raml-apis/Geonames#1]

**Comment by petrochenko-pavel-a** [comment]
`mediaTypeExtension` is a special parameter.
for`/resource{mediaTypeExtension}` you may set it with or without dot: `.json` or `json`, and in both cases ther resulting URI segment will be `/resource.json` (with dot!).

In GeoNames they have resources like `/resource` (which is XML) and `/resourceJSON` (without dot!), so we can not use `mediaTypeExtension` here.

`mediaTypeExtension` parameters makes notebooks look more nice, because it allows to use `.` for extension parameter instead of `()`.

**Comment by petrochenko-pavel-a** [comment]
Hi Also this is actually named `mediaTypeSuffix` for a reason (no dot in value, different and somewhat strange values are allowed for different resources (for example "", "JSON" and "CSV" for `countryInfo` resource)
